spring:
  application:
    name: trade-identity-service
  datasource:
    url: ${postgres_db_url}
    username: ${postgres_username}
    password: ${postgres_password}
    hikari:
      maximum-pool-size: 3
      minimum-idle: 0
      idle-timeout: 300000      # 5 min
      max-lifetime: 1800000     # 30 min
      keepalive-time: 0
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none   # you already created tables
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

security:
  jwt:
    issuer: "trade-identity-service"
    secret: ${security_jwt_secret}
    accessTtlMinutes: 15
  refresh:
    ttlDays: 30
  magicLink:
    ttlMinutes: 15

app:
  frontendBaseUrl: ${frontendBaseUrl}

logging:
  level:
    # Default log level for everything
    root: INFO
    # Your application packages (DEBUG for dev)
    com.amaravathi: INFO
    # Spring Web (controllers, filters)
    org.springframework.web: INFO
    # Spring Security (change to DEBUG only when needed)
    org.springframework.security: INFO
    # Hibernate / JPA
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql: INFO
  # Log patterns
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] cid=%X{cid} %logger{40} - %msg%n"



