spring:
  application:
    name: trade-identity-service
  datasource:
    url: ${postgres_db_url}
    username: ${postgres_username}
    password: ${postgres_password}
    hikari:
      maximum-pool-size: 3
      minimum-idle: 0
      idle-timeout: 300000      # 5 min
      max-lifetime: 1800000     # 30 min
      keepalive-time: 0
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none   # you already created tables
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

security:
  jwt:
    issuer: "trade-identity-service"
    secret: ${security_jwt_secret}
    accessTtlMinutes: 15
  refresh:
    ttlDays: 30
  magicLink:
    ttlMinutes: 15

app:
  frontendBaseUrl: ${frontendBaseUrl}

